source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import login_view, logout_view, RegisterView


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="registration")
]

source/api_v1/urls.py
from django.urls import path

from api_v1.views import (QuoteListCreateViewSet,
                          QuoteView,
                          QuoteCreateView,
                          QuoteUpdateViewSet,
                          QuoteDeleteViewSet,
                          QuoteRatingAddViewSet,
                          QuoteRatingRemoveViewSet)
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("login/", obtain_auth_token, name='api_token_auth'),
    path("quote/", QuoteListCreateViewSet.as_view(), name="quote"),
    path("quote/<int:pk>/", QuoteView.as_view(), name="quote_detail"),
    path("quote/create/", QuoteCreateView.as_view(), name="quote_create"),
    path("quote/<int:pk>/update/", QuoteUpdateViewSet.as_view(), name="quote_update"),
    path("quote/<int:pk>/delete/", QuoteDeleteViewSet.as_view(), name="quote_delete"),
    path("quote/<int:pk>/rating/add/", QuoteRatingAddViewSet.as_view(), name="quote_rating_add"),
    path("quote/<int:pk>/rating/remove/", QuoteRatingRemoveViewSet.as_view(), name="quote_rating_remove")

]

source/hello/urls.py
from django.contrib import admin
from django.urls import path, include

api_urlpatterns = [
    path("v1/", include('api_v1.urls'))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('webapp.urls')),
    path("api/", include(api_urlpatterns)),
    path("accounts/", include("accounts.urls"))
]

source/webapp/urls.py
from django.urls import path

from webapp.views import index

app_name = "webapp"

urlpatterns = [
    path("", index, name="index")
]

source/accounts/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models

STATUS_CHOICES = (("new", "Новая"), ("moderated", "Модеринован"))


class Quote(models.Model):
    text = models.TextField(max_length=2000,
                            blank=False,
                            null=False,
                            verbose_name="Текс")
    name = models.CharField(max_length=200,
                            null=True,
                            blank=True,
                            verbose_name="Имя")
    email = models.EmailField(max_length=30,
                              null=True,
                              blank=True,
                              verbose_name="Почтовый адрес")
    rating = models.PositiveIntegerField(default=0,
                                         verbose_name="Рейтинг")
    status = models.CharField(max_length=200,
                              choices=STATUS_CHOICES,
                              verbose_name="Статус",
                              default="new")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "quote"
        verbose_name = "Цитата"
        verbose_name_plural = "Цитаты"

    def __str__(self):
        return f"{self.status}"

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django import forms

User = get_user_model()

class MyUserCreationForm(UserCreationForm):
    email = forms.CharField(label="email", widget=forms.EmailInput, required=True)


    def clean(self):
        cleaned_data = super().clean()
        last_name = cleaned_data.get("last_name")
        first_name = cleaned_data.get("first_name")
        if not first_name:
            if not last_name:
                raise ValidationError("заполните хотя бы одно из полей: last_name, first_name")
        return cleaned_data

    class Meta(UserCreationForm.Meta):
        fields = ("username", "password1", "password2", "email", "first_name", "last_name")

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView

from accounts.forms import MyUserCreationForm

User = get_user_model()


class RegisterView(CreateView):
    model = User
    template_name = "registration.html"
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


def login_view(request):
    if request.user.is_authenticated:
        return redirect('webapp:index')
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')

source/api_v1/views.py
from rest_framework.generics import CreateAPIView, RetrieveAPIView, ListAPIView, UpdateAPIView, DestroyAPIView
from rest_framework.permissions import IsAdminUser
from api_v1.serializers import QuoteSerializer

from webapp.models import Quote


class QuoteListCreateViewSet(ListAPIView):
    serializer_class = QuoteSerializer

    def get_queryset(self):
        if self.request.user.is_staff:
            return Quote.objects.all()
        else:
            return Quote.objects.filter(status="moderated")


class QuoteView(RetrieveAPIView):
    serializer_class = QuoteSerializer

    def get_queryset(self):
        if self.request.user.is_staff:
            return Quote.objects.all()
        return Quote.objects.filter(status="moderated")


class QuoteCreateView(CreateAPIView):
    serializer_class = QuoteSerializer
    queryset = Quote.objects.all()


class QuoteUpdateViewSet(UpdateAPIView):
    permission_classes = [IsAdminUser]
    serializer_class = QuoteSerializer
    queryset = Quote.objects.all()


class QuoteDeleteViewSet(DestroyAPIView):
    permission_classes = [IsAdminUser]
    serializer_class = QuoteSerializer
    queryset = Quote.objects.all()

    def perform_destroy(self, instance):
        return instance.delete()


class QuoteRatingAddViewSet(UpdateAPIView):
    serializer_class = QuoteSerializer
    queryset = Quote.objects.all()

    def perform_update(self, serializer):

        if not f"rating_add_{serializer.instance.pk}" in self.request.session:
            self.request.session[f"rating_add_{serializer.instance.pk}"] = False

        if self.request.session[f"rating_add_{serializer.instance.pk}"] == False:
            serializer.instance.rating += 1
            serializer.instance.save()
            self.request.session[f"rating_add_{serializer.instance.pk}"] = True
            self.request.session[f"rating_remove_{serializer.instance.pk}"] = False

        return serializer


class QuoteRatingRemoveViewSet(UpdateAPIView):
    serializer_class = QuoteSerializer
    queryset = Quote.objects.all()

    def perform_update(self, serializer):

        if not f"rating_remove_{serializer.instance.pk}" in self.request.session:
            self.request.session[f"rating_remove_{serializer.instance.pk}"] = False

        if self.request.session[f"rating_remove_{serializer.instance.pk}"] == False:
            if not serializer.instance.rating == 0:
                serializer.instance.rating -= 1
                serializer.instance.save()
                self.request.session[f"rating_remove_{serializer.instance.pk}"] = True
                self.request.session[f"rating_add_{serializer.instance.pk}"] = False

        return serializer

source/webapp/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

source/accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <h1>Вход</h1>

    <form method="post" class="text-center ms-auto me-auto w-50">
        {% csrf_token %}
        {% if has_error == True %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        <button class="mt-3 btn btn-primary" type="submit">Войти</button>
    </form>
{% endblock %}

source/accounts/templates/registration.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    <form method="post">
        {% include "partial/form.html" with button_text="Зарегистрироваться" %}
    </form>
{% endblock %}

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}List articles{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href={% url 'webapp:index' %}>Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% block nav %}
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:registration' %}">Регистрация</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a>
                        </li>
                    {% endif %}
                {% endblock %}
            </ul>
            <button class="btn btn-secondary user-button" type="reset" onclick="modalCreateOpen()">Создать цитату
            </button>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
{% block scripts %}

{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="quote-list" id="quote-list">

        </div>
        <div id="myModal" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <span onclick="modalCreateClose()" class="close">×</span>
                    <h2>Создать Цитату</h2>
                </div>
                <div class="modal-body">
                    <form>
                        <br>
                        <input placeholder="Текс" class="input" maxlength="2000" type="text" required id="text">
                        <br>
                        <br>
                        <input placeholder="Имя" class="input" maxlength="200" type="text" id="name">
                        <br>
                        <br>
                        <input placeholder="Почта" class="input" maxlength="30" type="email" id="email">
                        <br>
                        <br>
                        <button onclick="createQuote()" type="submit" id="create-button">Создать</button>
                        <br>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script src="{% static "js/script.js" %}"></script>
    {% endblock %}

{% endblock %}

source/webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
   <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    {{ field }}
    <br/>

{% endfor %}


<input type="submit" value={{ button_text }} />